### ISSUE TITLE
It doesnt detect any obstacle. What should I do?

### ISSUE THREAD

**Issue by mustafamerttunali** [irtiq7/Obstacle-detection-algorithm-in-SimpleCV#1]
I need your help sir. How can I detect the obstacles? Your code doesnt work. I'm us'ng Logitech USB Camera.

**Comment by irtiq7** [comment]
What error message are you getting?

**Comment by mustafamerttunali** [comment]
Okey I can detect the circles but, how can I detect obstacles?

Example, the robot goes straight, if it detects a obstacle, it has to go left or right. I can do that with using ultrasonic sensor but I have to do that with using USB Camera. Any ideas? 

Have a nice day.

Edit: Obstacle could be any thing like box, keyboard and etc.

**Comment by irtiq7** [comment]
I am not sure what you mean. This algorithm detects obstacles that are
marked with a circular symbol. Based on the location of each circle, your
car will navigate accordingly ether left of right. If you want to detect
any generic obstacles then you should use stereo vision using two cameras.
